AvaliacaoMVC/Models/Alunos.cs
using System.ComponentModel.DataAnnotations;

namespace AvaliacaoMVC.Models
{
    public class Alunos
    {
        public int AlunosId { get; set; }

        [Display(Name ="Nome do Aluno")]
        [Required(ErrorMessage ="Informe o nome do aluno")]
        [StringLength(100, ErrorMessage = "Até 100 caracteres (min 5 caracteres)",MinimumLength =5)]
        public string? Nome { get; set; }

        [Range(3,70,ErrorMessage ="Idade entre 3 e 70 anos")]
        [Required(ErrorMessage = "Informe a idade do aluno")]
        public int Idade { get; set; }

        [Display(Name = "Endereço")]
        [Required(ErrorMessage = "Informe o endereço do aluno")]
        [StringLength(100)]
        public string? Endereco { get; set; }

        [Required(ErrorMessage = "Informe o CEP do aluno")]
        [StringLength(8,ErrorMessage ="CEP deve conter 8 numeros (sem traços ou espaços)")]
        public string? CEP { get; set; }

        [Required(ErrorMessage = "Informe a Turma do aluno")]
        [StringLength(20, ErrorMessage = "Até 50 carateres",MinimumLength =1)]
        public string? Turma { get; set; }

        [Display(Name = "Dia Pagamento")]
        public int DiaPagamento { get; set; }

        
        public double Mensalidade { get; set; }
    }
}

AvaliacaoMVC/Models/ErrorViewModel.cs
namespace AvaliacaoMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AvaliacaoMVC/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AvaliacaoMVC.Data;
using AvaliacaoMVC.Models;

namespace AvaliacaoMVC.Controllers
{
    public class AlunosController : Controller
    {
        private readonly AvaliacaoMVCContext _context;

        public AlunosController(AvaliacaoMVCContext context)
        {
            _context = context;
        }

        // GET: Alunos
        public async Task<IActionResult> Index(string searchString, string payDay)
        {
            if (_context.Alunos == null)
            {
                return Problem("Tabela inexistente");
            }
            var alunos = from m in _context.Alunos select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                alunos = alunos.Where(s => s.Nome!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(payDay))
            {
                alunos = alunos.Where(s => s.DiaPagamento.ToString()!.Contains(payDay));
            }
            return View(await alunos.ToListAsync());

        }

        // GET: Alunos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunosId == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // GET: Alunos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlunosId,Nome,Idade,Endereco,CEP,Turma")] Alunos alunos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alunos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos.FindAsync(id);
            if (alunos == null)
            {
                return NotFound();
            }
            return View(alunos);
        }

        // POST: Alunos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlunosId,Nome,Idade,Endereco,CEP,Turma,DiaPagamento,Mensalidade")] Alunos alunos)
        {
            if (id != alunos.AlunosId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alunos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunosExists(alunos.AlunosId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alunos);
        }

        // GET: Alunos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alunos = await _context.Alunos
                .FirstOrDefaultAsync(m => m.AlunosId == id);
            if (alunos == null)
            {
                return NotFound();
            }

            return View(alunos);
        }

        // POST: Alunos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var alunos = await _context.Alunos.FindAsync(id);
            if (alunos != null)
            {
                _context.Alunos.Remove(alunos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunosExists(int id)
        {
            return _context.Alunos.Any(e => e.AlunosId == id);
        }
    }
}

AvaliacaoMVC/Controllers/HomeController.cs
using AvaliacaoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AvaliacaoMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AvaliacaoMVC/Views/Alunos/Create.cshtml
@model AvaliacaoMVC.Models.Alunos

@{
    ViewData["Title"] = "Create";
}

<h4>Inclusão de Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-10">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="col-2">
                    <label asp-for="Idade" class="control-label"></label>
                    <input asp-for="Idade" class="form-control" />
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>
                <div class="col-9">
                    <label asp-for="Endereco" class="control-label"></label>
                    <input asp-for="Endereco" class="form-control" />
                    <span asp-validation-for="Endereco" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <label asp-for="CEP" class="control-label"></label>
                    <input asp-for="CEP" class="form-control" />
                    <span asp-validation-for="CEP" class="text-danger"></span>
                </div>
                <div class="col-5">
                    <label asp-for="Turma" class="control-label"></label>
                    <input asp-for="Turma" class="form-control" />
                    <span asp-validation-for="Turma" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group mt-4">
                    <input type="submit" value="Criar" class="btn btn-sm btn-primary" />
                    <a asp-action="Index" class="btn btn-sm btn-secondary">Voltar</a>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AvaliacaoMVC/Views/Alunos/Delete.cshtml
@model AvaliacaoMVC.Models.Alunos

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CEP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CEP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turma)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AlunosId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AvaliacaoMVC/Views/Alunos/Details.cshtml
@model AvaliacaoMVC.Models.Alunos

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Alunos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CEP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CEP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Turma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Turma)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.AlunosId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AvaliacaoMVC/Views/Alunos/Edit.cshtml
@model AvaliacaoMVC.Models.Alunos

@{
    ViewData["Title"] = "Edit";
}

<h4>Editar Alunos</h4>
<hr />
<div class="row">
    <div class="col-md-10">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AlunosId" />
            <div class="row">
                <div class="col-10">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="col-2">
                    <label asp-for="Idade" class="control-label"></label>
                    <input asp-for="Idade" class="form-control" />
                    <span asp-validation-for="Idade" class="text-danger"></span>
                </div>
                <div class="col-9">
                    <label asp-for="Endereco" class="control-label"></label>
                    <input asp-for="Endereco" class="form-control" />
                    <span asp-validation-for="Endereco" class="text-danger"></span>
                </div>
                <div class="col-3">
                    <label asp-for="CEP" class="control-label"></label>
                    <input asp-for="CEP" class="form-control" />
                    <span asp-validation-for="CEP" class="text-danger"></span>
                </div>
                <div class="col-5">
                    <label asp-for="Turma" class="control-label"></label>
                    <input asp-for="Turma" class="form-control" />
                    <span asp-validation-for="Turma" class="text-danger"></span>
                </div>
                 <div class="col-2">
                    <label asp-for="DiaPagamento" class="control-label"></label>
                    <input asp-for="DiaPagamento" class="form-control" />
                    <span asp-validation-for="DiaPagamento" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="form-group mt-4">
                    <input type="submit" value="Alterar" class="btn btn-sm btn-primary" />
                    <a asp-action="Index" class="btn btn-sm btn-secondary">Voltar</a>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

AvaliacaoMVC/Views/Alunos/Index.cshtml
@model IEnumerable<AvaliacaoMVC.Models.Alunos>

@{
    ViewData["Title"] = "Lista de Alunos";
}

<h1>Lista de Alunos</h1>

<p>
    <a asp-action="Create" class="btn btn-sm btn-success">Criar novo Aluno</a>
</p>

<form asp-controller="Alunos" asp-action="Index">
    <div class="d-flex align-items-center">
        <div class="col-sm-6 px-3">
            Nome do Aluno: <input type="text" name="searchString" class="form-control form-control-sm" />
        </div>
        <div class="col-sm-2 px-3">
            Data pgto: <input type="number" name="payDay" class="form-control form-control-sm" />
        </div>
        <div class="col-sm-3">
            <input type="submit" value="Filtrar" class="btn btn-sm btn-outline-secondary mt-4" />
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CEP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Turma)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DiaPagamento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Idade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Endereco)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CEP)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Turma)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaPagamento)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.AlunosId" class="btn btn-sm btn-success"><i class="bi bi-pen"></i> Editar</a>
                    <a asp-action="Details" asp-route-id="@item.AlunosId" class="btn btn-sm btn-secondary"><i class="bi bi-card-list"></i> Detalhes</a>
                    <a asp-action="Delete" asp-route-id="@item.AlunosId" class="btn btn-sm btn-danger"><i class="bi bi-file-earmark-x"></i> Apagar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AvaliacaoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AvaliacaoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvaliacaoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvaliacaoMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvaliacaoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AvaliacaoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AvaliacaoMVC/Views/Shared/_LayoutTEMPLATE.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Avaliação MVC</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="~/vendor/css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" href="~/vendor/css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="~/vendor/css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="~/vendor/images/fevicon.png" type="~/vendor/image/gif" />
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->
<body class="main-layout inner_page">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="~/vendor/images/loading.gif" alt="#" /></div>
    </div>
    <!-- end loader -->
    <!-- header -->
    <div class="header">
        <div class="container-fluid">
            <div class="row d_flex">
                <div class=" col-md-2 col-sm-3 col logo_section">
                    <div class="full">
                        <div class="center-desk">
                            <div class="logo">
                                <a href="index.html"><img src="~/vendor/images/logo.png" alt="#" /></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8 col-sm-12">
                    <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="index.html">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="skating.html">skating</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="shop.html">shop</a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="contact.html">Contact Us</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>
                <div class="col-md-2">
                    <ul class="email text_align_right">
                        <li class="d_none"><a href="Javascript:void(0)"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                        <li class="d_none"> <a href="Javascript:void(0)"><i class="fa fa-search" style="cursor: pointer;" aria-hidden="true"></i></a> </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- end header inner -->
    @RenderBody()
    <!--  footer -->
    @* <footer>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 ">
                        <div class="infoma">
                            <h3>Contact Us</h3>
                            <ul class="conta">
                                <li>
                                    <i class="fa fa-map-marker" aria-hidden="true"></i>Locations
                                </li>
                                <li><i class="fa fa-phone" aria-hidden="true"></i>Call +01 1234567890</li>
                                <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="Javascript:void(0)"> demo@gmail.com</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="row border_left">
                            <div class="col-md-12">
                                <div class="infoma">
                                    <h3>Newsletter</h3>
                                    <form class="form_subscri">
                                        <div class="row">
                                            <div class="col-md-12">
                                            </div>
                                            <div class="col-md-4">
                                                <input class="newsl" placeholder="Enter your email" type="text" name="Enter your email">
                                            </div>
                                            <div class="col-md-4">
                                                <input class="newsl" placeholder="Enter your email" type="text" name="Enter your email">
                                            </div>
                                            <div class="col-md-4">
                                                <button class="subsci_btn">subscribe</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-9">
                                <div class="infoma">
                                    <h3>Useful Link</h3>
                                    <ul class="fullink">
                                        <li><a href="index.html">Home</a></li>
                                        <li><a href="about.html">About</a></li>
                                        <li><a href="skating.html">Skating</a></li>
                                        <li><a href="shop.html">Shop</a></li>
                                        <li><a href="contact.html">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="infoma text_align_left">
                                    <ul class="social_icon">
                                        <li><a href="Javascript:void(0)"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                                        <li><a href="Javascript:void(0)"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                                        <li><a href="Javascript:void(0)"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a></li>
                                        <li><a href="Javascript:void(0)"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <p>© 2020 All Rights Reserved. Design by <a href="https://html.design/"> Free html Templates</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer> *@
    <!-- end footer -->
    <!-- Javascript files-->
    <script src="~/vendor/js/jquery.min.js"></script>
    <script src="~/vendor/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/js/jquery-3.0.0.min.js"></script>
    <!-- sidebar -->
    <script src="~/vendor/js/custom.js"></script>
    <script>
        AOS.init();
    </script>
</body>
</html>